### ISSUE TITLE
Schlüsselbesitz auf Profilseite

### ISSUE THREAD

**Issue by idnovic** [rmbinder/KeyManager#23]
Ist es möglich auf der Profilseite eines jeweiligen Mitglieds die zugeordneten Schlüssel anzuzeigen?

Wenn Mitglied A einen Schlüssel erhält, Wäre es möglich, dass Mitglied A auf der eigenen Profilseite den Schlüsselbesitzt sieht? Ähnlich wie die Gruppenzugehörigkeit.

**Comment by rmbinder** [comment]
Ja, das sollte möglich sein.
Das Plugin Awards verwendet ein ähnliches Konstrukt und zeigt die verliehenen Auszeichnungen auf der Profilseite an.
Ich versuche mal das einzubauen.

**Comment by idnovic** [comment]
Ein anderes Anliegen, (ich würde ein anderes Issue erstellen, falls machbar/bejaht)

Wir verwalten Fahrradhaken. Also Hakennummern für Fahrradstellplätze. 
Ich überlege dieses Plugin zu forken und die Beschreibungen zu ändern. 

Alternativ, wäre es möglich dieses Plugin durch Kategorien oder Arten von Schlüsseln zu erweitern?

Beispiele:
Schlüssel,
Briefkasten,
Fahrradhaken,
Code Türschloss,
Pin...

Dann müsste das Plugin nicht einen Schlüssel anzeigen sondern jeweils die Arten unterscheiden können und auf den Profilseiten richtig benennen. 

Das würde die Möglichkeiten erweitern. 
z.B. könnten auch Zugangsdaten jeweiligen Mitgliedern zugeordnet werden. Pin 1234 für das Türschloss für Mitglied A. Das Mitglied sieht das dann auf deren Profilseite.

**Comment by rmbinder** [comment]
Für ein neues Thema bitte ein anderes Issue erstellen.

**Comment by idnovic** [comment]
Danke dir!

**Comment by rmbinder** [comment]
Eine Einstellmöglichkeit ist auch vorhanden:
-->"Einstellungen-Einstellungen für die Profilansicht"
