### ISSUE TITLE
Pluginerweiterung durch Kategorien oder Arten von Schlüsseln

### ISSUE THREAD

**Issue by rmbinder** [rmbinder/KeyManager#24]
Ein anderes Anliegen, (ich würde ein anderes Issue erstellen, falls machbar/bejaht)

Wir verwalten Fahrradhaken. Also Hakennummern für Fahrradstellplätze. 
Ich überlege dieses Plugin zu forken und die Beschreibungen zu ändern. 

Alternativ, wäre es möglich dieses Plugin durch Kategorien oder Arten von Schlüsseln zu erweitern?

Beispiele:
Schlüssel,
Briefkasten,
Fahrradhaken,
Code Türschloss,
Pin...

Dann müsste das Plugin nicht einen Schlüssel anzeigen sondern jeweils die Arten unterscheiden können und auf den Profilseiten richtig benennen. 

Das würde die Möglichkeiten erweitern. 
z.B. könnten auch Zugangsdaten jeweiligen Mitgliedern zugeordnet werden. Pin 1234 für das Türschloss für Mitglied A. Das Mitglied sieht das dann auf deren Profilseite.

_Originally posted by @idnovic in https://github.com/rmbinder/KeyManager/issues/23#issuecomment-1028846440_

**Comment by rmbinder** [comment]
_Ich überlege dieses Plugin zu forken und die Beschreibungen zu ändern._
Vielleicht reicht es, die Sprachdatei (.xml) anzupassen.

_Alternativ, wäre es möglich dieses Plugin durch Kategorien oder Arten von Schlüsseln zu erweitern?_
--> Viel Arbeit
Wie wäre es, über die Sprachdatei den Text "Schlüsselname" in einen allgemeingültigen Text abzuändern und zusätzliche Schlüsselfelder (Briefkasten, Fahrradhaken......) anzulegen?

**Comment by idnovic** [comment]
Das klingt gut. 
Bin mir noch nicht sicher wie genau das gemeint ist. Ich erstelle später ein paar Schlüssel um mir das genau anzuschauen. 

Aktuell verstehe ich das so, das ich mehrerer Schlüssel anlegen kann. 
Diese Schlüssel haben Felder in der DB. 
Ich fülle nur das nötige Feld aus (Fahrradhakennummer). 
Der Schlüssel A1 ist somit ein Fahrradhaken. 

Später auf der Profilseite von Person A wird dann der Schlüssel mit nur den ausgefüllten Feldern angezeigt?

Dann müsste ich das nicht forken. Solange der Datentyp Name und Datentyp Inhalt sichtbar sind.
z.B. Schlüssel
Name von Schlüssel Haken A1
Feldname Fahrradhaken
Feldinhalt A1

Habe ich das richtig verstanden?

**Comment by rmbinder** [comment]
Du kannst über "Einstellungen-Schlüsselfelder pflegen" neue Schlüsselfelder anlegen. Also wie "Schlüsselname" oder "Empfänger" einfach neue Felder. Das könnte z.B. ein Dropdown-Listenfeld sein, mit den Wahlmöglichkeiten "Schlüssel, Briefkasten, Fahrradhaken usw".

**Comment by idnovic** [comment]
Ich habe mich entschieden den Ratschlag zu befolgen. 
Jedoch muss ich dennoch das Plugin forken. 
Während Schlüssel vom Vorstand ausgegeben werden, sollen die Fahrradhakennummern von einem normalen Mitglied verwaltet werden. 

Damit das mit den Plugin Zugriffsrechten in Ordnung geht, brauche ich also einen Fork. 

Auf welche Dinge muss ich im Sourcode achten, damit ich einen Fork neben dem Original gleichzeitig verwenden kann?
Ganz besonders interessieren mich nötige Umbenennung bei der Datenbank.

**Comment by rmbinder** [comment]
Die Tabellennamen sind in der common_function.php definiert (über define...). Der Name der Tabelle, in der die Konfiguration gespeichert ist (adm_plugin_preferences), ist in der configtable.php  definiert.  Evtl. hilft hier einfaches Umbenennen der Tabellennamen.
